export enum UserPerm {
	UserList = 'user_list',
	UserCreate = 'user_create',
	UserRead = 'user_read',
	UserUpdate = 'user_update',
	UserDelete = 'user_delete',
	UserVerify = 'user_verify',
	UserActivate = 'user_activate',
	UserDeactivate = 'user_deactivate',
	UserResetPassword = 'user_reset_password',
	UserRoleList = 'user_role_list',
	UserRoleAdd = 'user_role_add',
	UserRoleRemove = 'user_role_remove',
	UserPermissionList = 'user_permission_list',
	UserPermissionAdd = 'user_permission_add',
	UserPermissionRemove = 'user_permission_remove',
	RoleList = 'role_list',
	RoleCreate = 'role_create',
	RoleRead = 'role_read',
	RoleUpdate = 'role_update',
	RoleDelete = 'role_delete',
	PaymentList = 'payment_list',
	PaymentCreate = 'payment_create',
	PaymentRead = 'payment_read',
	PaymentUpdate = 'payment_update',
	PaymentDelete = 'payment_delete',
	PermissionList = 'permission_list',
	PermissionCreate = 'permission_create',
	PermissionRead = 'permission_read',
	PermissionUpdate = 'permission_update',
	PermissionDelete = 'permission_delete',

	Impossible = 'impossible',
}
